#!/bin/bash
code --install-extension 4ops.terraform
code --install-extension alefragnani.project-manager
code --install-extension atlassian.atlascode
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension GabrielBB.vscode-lombok
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension jebbs.plantuml
code --install-extension johnpapa.vscode-peacock
code --install-extension JonaNeumeier.endpoints
code --install-extension karigari.chat
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension octref.vetur
code --install-extension orsenkucher.vscode-graphql
code --install-extension Pivotal.vscode-concourse
code --install-extension Pivotal.vscode-manifest-yaml
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ronnidc.nunjucks
code --install-extension ryu1kn.partial-diff
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension SimonSiefke.svg-preview
code --install-extension TabNine.tabnine-vscode
code --install-extension Yog.yog-plantuml-highlight
code --install-extension ziyasal.vscode-open-in-github
