[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]] #Vim用の統合ユーザインターフェース
repo = 'Shougo/unite.vim'

[[plugins]] #カラースキーマ
repo = 'tomasr/molokai'

[[plugins]] #インデントに色をつけてくれるプラグイン
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] #Vimのサイドバーにディレクトリツリーを一覧表示することができるプラグイン
repo = 'scrooloose/nerdtree'

[[plugins]] #VimからGitコマンドを実行できるプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]] #複数の検索結果を異なる色でハイライトすることができるプラグイン
repo = 't9md/vim-quickhl'

[[plugins]] #ビジュアルモードで選択した文字列を検索することができるプラグイン
repo = 'thinca/vim-visualstar'

[[plugins]] #ファイル名で検索し、そのままVim上で開くことができるプラグイン
repo = 'kien/ctrlp.vim'

[[plugins]] #Zen-Codingの後継という位置づけのプラグイン
repo = 'mattn/emmet-vim'

[[plugins]] #コードを自動補完してくれるプラグイン
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]] #スニペット機能をVimに追加するためのプラグイン
repo = 'Shougo/neosnippet.vim'

[[plugins]] #コメントアウトの解除をしたりしてくれるプラグイン
repo = 'tomtom/tcomment_vim'

[[plugins]] #HTMLタグなどの編集ができるプラグイン<Paste>
repo = 'tpope/vim-surround'

[[plugins]] #Vimで線を描画するためのプラグイン
repo = 'vim-scripts/DrawIt'

#[[plugins]] #Vimの変数を整形して出力してくれるプラグイン
#repo = 'vim-prettyprint/tree/master'

[[plugins]] #HTML5のシンタックスチェックするプラグイン
repo = 'hokaccha/vim-html5validator'

[[plugins]] #シンタックスチェックしてくれるプラグイン
repo = 'scrooloose/syntastic'

[[plugins]] #シンタックスチェックを非同期処理で行ってくれるプラグイン
repo = 'osyo-manga/vim-watchdogs'

#[[plugins]] #選択したテキストオブジェクトをレジスタ文字列に置換するoperatorプラグイン
#repo = 'kana/vim-operator-replace'

#[[plugins]] #選択したテキストオブジェクトをソートするoperatorプラグイン
#repo = 'emonkak/vim-operator-sort'

#[[plugins]] #選択したテキストオブジェクトをコメント、アンコメントするためのoperatorプラグイン
#repo = 'vim-operator-comment'

# other plugins
# 

[[plugins]]
repo = 'fatih/vim-go.git'

